# Generated by Django 3.1.6 on 2021-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forms', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/posts'),
        ),
    ]
