# Generated by Django 3.1.6 on 2021-02-10 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forms', '0004_auto_20210209_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='face',
        ),
    ]
