# Generated by Django 3.1.6 on 2021-02-10 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forms', '0005_auto_20210210_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
