# Generated by Django 3.1.6 on 2021-02-11 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forms', '0006_auto_20210210_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='face',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
