# Generated by Django 3.1.6 on 2021-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20210212_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='episode',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='videolink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
