# Generated by Django 3.1.6 on 2021-02-28 16:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('forms', '0008_auto_20210223_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
