# Generated by Django 3.1.6 on 2021-03-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('forms', '0009_auto_20210228_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='episode',
            new_name='episodeen',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='videolink',
            new_name='videolinken',
        ),
        migrations.AddField(
            model_name='post',
            name='episoderaw',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='episodeth',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='videolinkraw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='videolinkth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
