# Generated by Django 3.1.7 on 2021-03-15 12:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=10)),
                ('social', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=10000)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
