# Generated by Django 3.1.7 on 2021-03-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_friend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='friend',
            new_name='FriendList',
        ),
    ]
