# Generated by Django 3.1.7 on 2021-03-15 16:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_auto_20210315_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
