# Generated by Django 3.1.7 on 2021-03-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20210315_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlist',
            options={'verbose_name_plural': 'friend'},
        ),
    ]
