# Generated by Django 3.1.7 on 2021-03-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_auto_20210315_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='picture',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
