# Generated by Django 3.1.7 on 2021-03-15 16:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_friendlist_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='image',
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='picture'),
        ),
    ]
