# Generated by Django 3.1.7 on 2021-03-15 16:59

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20210315_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=2, upload_to='images/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendlist',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='picture',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
