# Generated by Django 3.1.7 on 2021-03-15 17:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_auto_20210315_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='friendlist',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='picture'),
        ),
    ]
