# Generated by Django 3.1.7 on 2021-03-15 18:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20210316_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=10)),
                ('social', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=10000)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='picture')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'friendzone',
            },
        ),
    ]
