# Generated by Django 3.1.7 on 2021-03-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_friendzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendzone',
            name='message2',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
